image: Visual Studio 2017

platform: Any CPU
configuration: Release

before_build:
 - nuget restore Project/Galagram.sln

build:
 verbosity: minimal
 publish_wap: true
 project: Project/Core.csproj
 project: Project/DataAccess.csproj 
 project: Project/Galagram.csproj 
